# Generated by Django 4.2 on 2023-05-08 19:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import rental_ads.models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Rental', 'verbose_name_plural': 'Rentals'},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='image',
        ),
        migrations.AddField(
            model_name='rental',
            name='address',
            field=models.CharField(default='provide_value', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RentalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=rental_ads.models.rental_image_upload_path)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rental_ads.rental')),
            ],
            options={
                'verbose_name': 'Rental Image',
                'verbose_name_plural': 'Rental Images',
            },
        ),
    ]
