# Generated by Django 4.2.1 on 2023-05-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0002_auto_20230507_2300'),
    ]

    operations = [
    ]
