# Generated by Django 4.2 on 2023-05-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0003_contact'),
        ('rental_ads', '0004_auto_20230507_2321'),
    ]

    operations = [
    ]
