# Generated by Django 4.2.1 on 2023-05-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0007_rental_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
