# Generated by Django 4.2.1 on 2023-05-21 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0009_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
