# Generated by Django 4.2.1 on 2023-05-21 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_ads', '0011_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='Favorites',
        ),
        migrations.AddField(
            model_name='rental',
            name='favorite_users',
            field=models.ManyToManyField(related_name='favorite_rentals', through='rental_ads.Favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
