# Generated by Django 4.2.1 on 2023-05-21 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rental_ads', '0013_remove_rental_favorite_users_delete_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_rentals', to=settings.AUTH_USER_MODEL),
        ),
    ]
