# Generated by Django 4.2.1 on 2023-05-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0014_rental_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='favorites',
        ),
    ]
