# Generated by Django 4.2.1 on 2023-05-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0019_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
