# Generated by Django 4.2.1 on 2023-05-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_ads', '0022_rename_receiver_message_recipient_message_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sender_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
